import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.io.*;
import java.text.*;
import java.util.*;
import java.sql.*;
public class ConnectMySQL {
	static Connection conn = null;
	static String dbServer = " ";
	static String dbServerPort = "3306";
	static String url = "jdbc:mysql://195.251.249.131:3306/ismgroup28?user=ismgroup28";
	static String dbName = "ismgroup28";
	static String dbusername = "ismgroup28";
	static String dbpassword = "v9c5dm";
	public static void now() throws IllegalAccessException, InstantiationException, ClassNotFoundException, SQLException {
		Class.forName("com.mysql.jdbc.Driver").newInstance();
		conn = DriverManager.getConnection(url, dbusername, dbpassword);	
		if (conn != null) {
			System.out.println("OK");
		}
		Statement stmt = conn.createStatement();
		ResultSet rs1 = stmt.executeQuery("SELECT * FROM Products");
		String x1;
		String x2;
		String x3;
		String x4;
		String x5;
		String x6;
		String x7;
		int y1;
		int y2;
		int y3;
		int y4;
		double y5;
		while (rs1.next()){
		x1 = rs1.getString("IDPRODUCT");
		y1 = Integer.parseInt(x1);
		x2 = rs1.getString("NAMEPRODUCT");		
		x3 = rs1.getString("DESCRIPTION");
		x4 = rs1.getString("VOLUME");
		y2 = Integer.parseInt(x4);
		x5 = rs1.getString("MINQUANTITY");
		y3 = Integer.parseInt(x5);
		x6 = rs1.getString("STOCK");
		y4 = Integer.parseInt(x6);
		x7 = rs1.getString("PRICE");
		y5 = Float.parseFloat(x7);
		new Stock(y1, x2, x3, y2, y3, y4, y5);
		}
		ResultSet rs2 = stmt.executeQuery("SELECT * FROM CUSTOMERS");
		String z1;
		String z2;
		String z3;
		String z4;
		String z5;
		String z6;
		String z7;
		int l1;
		int l2;
		int l3;
		double k1;
		while (rs2.next()) {
			z1 = rs2.getString("IDCUSTOMER");
			l1 = Integer.parseInt(z1);
			z2 = rs2.getString("NAMECUSTOMER");
			z3 = rs2.getString("PHONE");
			z4 = rs2.getString("ADDRESS");
			z5 = rs2.getString("YEARS_OF_COOPERATION");
			l2 = Integer.parseInt(z5);
			z6 = rs2.getString("PERCENT_OF_STOCK");
			k1 = Float.parseFloat(z6);
			z7 = rs2.getString("CREADITWORTHINESS");
			l3 = Integer.parseInt(z7);
		}
		ResultSet rs3 = stmt.executeQuery("SELECT * FROM ORDERS");
		int w1;
		int w2;
		String w3;
		String w4;
		int p1;
		int p2;
		String p3;
		int p4;
		double p5;
		int p6;
		String p7;
		int p8;
		double p9;
		int p10;
		String p11;
		int p12;
		double p13;
		int p14;
		String p15;
		int p16;
		double p17;
		int p18;
		String p19;
		int p20;
		double p21;
		while (rs3.next()) {
			w1 = Integer.parseInt(rs3.getString("IDORDER"));
			w2 = Integer.parseInt(rs3.getString("IDCUSTOMER"));
			w3 = rs3.getString("NAMECUSTOMER");
			w4 = rs3.getString("DATE_OF_ORDER");
			p2 = Integer.parseInt(rs3.getString("IDPRODUCT1"));
			p3 = rs3.getString("NAMEPRODUCT1");
			p4 = Integer.parseInt(rs3.getString("QUANTITY1"));
			p5 = Float.parseFloat(rs3.getString("PRICE1"));
			p6 = Integer.parseInt(rs3.getString("IDPRODUCT2"));
			p7 = rs3.getString("NAMEPRODUCT2");
			p8 = Integer.parseInt(rs3.getString("QUANTITY2"));
			p9 = Float.parseFloat(rs3.getString("PRICE2"));
			p10 = Integer.parseInt(rs3.getString("IDPRODUCT3"));
			p11 = rs3.getString("NAMEPRODUCT3");
			p12 = Integer.parseInt(rs3.getString("QUANTITY3"));
			p13 = Float.parseFloat(rs3.getString("PRICE3"));
			p14 = Integer.parseInt(rs3.getString("IDPRODUCT4"));
			p15 = rs3.getString("NAMEPRODUCT4");
			p16 = Integer.parseInt(rs3.getString("QUANTITY4"));
			p17 = Float.parseFloat(rs3.getString("PRICE4"));
			p18 = Integer.parseInt(rs3.getString("IDPRODUCT5"));
			p19 = rs3.getString("NAMEPRODUCT5");
			p20 = Integer.parseInt(rs3.getString("QUANTITY5"));
			p21 = Float.parseFloat(rs3.getString("PRICE5"));
			new Order(w1, w2, w3, w4, p2, p3, p4, p5, p6, p7, p8, p9, p10, p11, p12, p13, p14, p15, p16, p17, p18, p19, p20, p21);
		}
		ResultSet rs4 = stmt.executeQuery("SELECT * FROM DINSTANCEMATRIX");
		int e1;
		int e2;
		int e3;
		int e4;
		int e5;
		int e6;
		int e7;
		int e8;
		int e9;
		int e10;
		int e11;
		int e12;
		while (rs4.next()) {
			e1 = Integer.parseInt(rs4.getString("A"));
			e2 = Integer.parseInt(rs4.getString("B"));
			e3 = Integer.parseInt(rs4.getString("C"));
			e4 = Integer.parseInt(rs4.getString("D"));
			e5 = Integer.parseInt(rs4.getString("E"));
			e6 = Integer.parseInt(rs4.getString("F"));
			e7 = Integer.parseInt(rs4.getString("G"));
			e8 = Integer.parseInt(rs4.getString("H"));
			e9 = Integer.parseInt(rs4.getString("I"));
			e10 = Integer.parseInt(rs4.getString("J"));
			e11 = Integer.parseInt(rs4.getString("K"));
		}
		rs1.close();
		rs2.close();
		rs3.close();
		rs4.close();
		stmt.close();
	}
}